-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.configs
(
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	bitbucket_repository varchar NULL,
	bitbucket_username varchar NULL,
	bitbucket_password varchar NULL,
	flock_channel varchar NULL,
	flock_review_channel varchar NULL,
	pr_authors text NULL,
	active bool NOT NULL DEFAULT true,
	custom_greeter bool NULL DEFAULT true,
	created_at timestamptz NULL DEFAULT now(),
	updated_at timestamptz NULL,
	CONSTRAINT configs_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.configs
    OWNER to postgres;

GRANT ALL ON TABLE public.configs TO anon;

GRANT ALL ON TABLE public.configs TO authenticated;

GRANT ALL ON TABLE public.configs TO postgres;

GRANT ALL ON TABLE public.configs TO service_role;
