-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.configs
(
    id bigint NOT NULL,
    bitbucket_repository character varying(255) COLLATE pg_catalog."default" NOT NULL,
    bitbucket_username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    bitbucket_password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    flock_channel character varying(255) COLLATE pg_catalog."default" NOT NULL,
    flock_review_channel character varying(255) COLLATE pg_catalog."default",
    pr_authors text COLLATE pg_catalog."default" NOT NULL,
    active boolean,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone,
    CONSTRAINT configs_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.configs
    OWNER to postgres;

GRANT ALL ON TABLE public.configs TO anon;

GRANT ALL ON TABLE public.configs TO authenticated;

GRANT ALL ON TABLE public.configs TO postgres;

GRANT ALL ON TABLE public.configs TO service_role;
